Expose viewpoint values
videolan/vlckit pull request #7
Opened 2018-04-24 14:42 UTC by carolanitz

2018-04-24 17:22 UTC, fkuehne requested changes
Minor nit-picks.

2018-04-24 17:22 UTC, fkuehne commented on Sources/VLCMediaPlayer.m
> +    [self viewPoint]->f_field_of_view = fov;
Those four setters are not safe for 32bit as CGFloat is 64bit for 64bit architectures while 32bit for 32bit architectures. VLC's variables however are always 32bit.

2018-04-24 17:22 UTC, fkuehne commented on Headers/Public/VLCMediaPlayer.h
> + * Set/Get the adjust filter's gamma value
ehm.

2018-04-24 17:22 UTC, fkuehne commented on Headers/Public/VLCMediaPlayer.h
> + * \param fov new field of view.  field of view in degrees ]0;180[ (default 80.)
I would totally remove the old comments and just use your new ones as those are lot more understandable.

2018-04-26 08:52 UTC, chouquette commented on Sources/VLCMediaPlayer.m
> +    [self viewPoint]->f_field_of_view = fov;
Hm, are you sure? VLC's integer variables are int64_t

2018-04-26 16:32 UTC, fkuehne commented on Sources/VLCMediaPlayer.m
> +    [self viewPoint]->f_field_of_view = fov;
Sure, for integer there is no such problem. However, https://www.videolan.org/developers/vlc/doc/doxygen/html/structlibvlc__video__viewpoint__t.html states simply "float".

2018-04-27 07:21 UTC, tguillem commented on Sources/VLCMediaPlayer.m
> -        NSAssert(_viewpoint != nil, @"Viewpoint wasn't allocated");
indeed, alloc errors should not be checked with an assert

2018-04-27 07:23 UTC, tguillem commented on Sources/VLCMediaPlayer.m
>          _viewpoint = libvlc_video_new_viewpoint();
You should maybe create this variable from the VLCMediaPlayer constructor, and handle the alloc fail here.
That way, you are sure that _viewpoint can't be NULL during the live cycle of the object.

2018-04-27 07:40 UTC, carolanitz commented on Sources/VLCMediaPlayer.m
>          _viewpoint = libvlc_video_new_viewpoint();
but it's still fine if it is. You just can't pan or change the viewpoint

2018-04-27 07:58 UTC, tguillem commented on Sources/VLCMediaPlayer.m
>          _viewpoint = libvlc_video_new_viewpoint();
Yes it is fine. But when possible, I prefer to initialize/allocate small structures/classes in the init function. That way, you don't have to handle the case where the object is null in the other part of code. This make the code simpler IMHO.

2018-04-30 09:19 UTC, carolanitz commented
this was merged with 3650673ac6cd121729c15b131c6d070e31f67bbc

2018-04-30 09:19 UTC, closed without merging